-- {{SERVICE_NAME}} - Database initialization
-- Generated by GX Genesis | Team: {{TEAM}} | Tier: {{TIER}}

-- Create extensions commonly needed for Galaxy services
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "btree_gin";
CREATE EXTENSION IF NOT EXISTS "pg_stat_statements";

-- Comment for Galaxy tracking
COMMENT ON EXTENSION "uuid-ossp" IS 'Galaxy standard - UUID generation';
COMMENT ON EXTENSION "pgcrypto" IS 'Galaxy standard - Cryptographic functions';