# infra-smoke-postgres - PostgreSQL database for smoke tests
# Generated by GX Genesis | Team: team3 | Tier: infra | Eco: gx-smoke
FROM postgres:16

# Labels for Galaxy platform
LABEL service.name="infra-smoke-postgres" \
      service.tier="infra" \
      service.workload="infra" \
      service.team="team3" \
      service.eco="gx-smoke" \
      galaxy.io/managed-by="galaxy"

# Install system dependencies for infrastructure services
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    wget \
    gnupg \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Copy initialization scripts
COPY init/*.sql /docker-entrypoint-initdb.d/

# Set proper permissions
RUN chmod -R 755 /docker-entrypoint-initdb.d/

# Expose Postgres default port (5432)
EXPOSE 5432

# Custom health check for Postgres
HEALTHCHECK --interval=30s --timeout=10s --start-period=30s --retries=3 \
    CMD pg_isready -U $POSTGRES_USER -d $POSTGRES_DB || exit 1

# Use default Postgres entrypoint and command
