# {{SERVICE_NAME}} - {{DESCRIPTION}}
# Generated by GX Genesis | Team: {{TEAM}} | Tier: {{TIER}} | Eco: {{ECO_NAME}}
FROM postgres:16

# Labels for Galaxy platform
LABEL service.name="{{SERVICE_NAME}}" \
      service.tier="{{TIER}}" \
      service.workload="{{TIER}}" \
      service.team="{{TEAM}}" \
      service.eco="{{ECO_NAME}}" \
      galaxy.io/managed-by="galaxy"

# Install system dependencies for infrastructure services
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    wget \
    gnupg \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Copy initialization scripts
COPY init/*.sql /docker-entrypoint-initdb.d/

# Set proper permissions
RUN chmod -R 755 /docker-entrypoint-initdb.d/

# Expose Postgres default port (5432)
EXPOSE 5432

# Custom health check for Postgres
HEALTHCHECK --interval=30s --timeout=10s --start-period=30s --retries=3 \
    CMD pg_isready -U $POSTGRES_USER -d $POSTGRES_DB || exit 1

# Use default Postgres entrypoint and command
