{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "service.fullname" . }}-secrets
  namespace: {{ include "service.namespace" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Dynamically load all secrets from workspace secrets.yaml
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
{{- end }}